version: '3.9'
services:
    zookeeper:
        image: lgslm/zookeeper:v1.0.0
        hostname: zookeeper
        container_name: zookeeper
        environment:
            - MYID=1
        expose:
            - "2181"
        ports:
            - "2181:2181"
        networks:
          - kafka-clients-net
    kafka:
        image: lgslm/kafka:v1.0.0
        hostname: kafka
        container_name: kafka
        environment:
            - SERVICE_PRECONDITION=zookeeper:2181
            - ZOOKEEPER_SERVERS=zookeeper:2181
            - TOPIC=taxi
        depends_on:
            - zookeeper
        expose:
            - "9092"
        networks:
          - kafka-clients-net

networks:
        kafka-clients-net:
            external: true
