version: '3.2'
services:
    zookeeper:
        image: lgslm/zookeeper
        hostname: zookeeper
        container_name: zookeeper
        environment:
            - MYID=1
        expose:
            - "2181"
        ports:
            - "2181:2181"
    kafka:
        image: lgslm/kafka
        hostname: kafka
        container_name: kafka
        environment:
            - SERVICE_PRECONDITION=zookeeper:2181
            - ZOOKEEPER_SERVERS=zookeeper:2181
            - INITIAL_TOPICS="taxi"
        depends_on:
            - zookeeper
        expose:
            - "9092"
