#!/bin/bash

set -e

export R=$( (nc -z localhost 9092) && echo ok )

if [[ "$R" == "ok" ]]; then
    if [[ -z "$TOPIC" ]] ;then
        exit 0
    else
        test -e /TOPIC_AVAILABLE
        exit $?
    fi
    exit 0
else
    exit 1
fi
